export const blogPosts = [
  {
    _id: "1",
    title: "Getting Started with Next.js Routing",
    slug: "nextjs-routing-guide",
    description: "A beginner-friendly guide to understanding file-based routing in Next.js, with examples for dynamic routes and nested structures.",
    author: "Amir Hamza Ismail",
    categories: ["Next.js", "Web Development"],
    featuredImage: "https://images.unsplash.com/photo-1581091215367-59ab6f0c2caa",
    status: "published",
    views: 320,
    likes: 25,
    commentsCount: 4,
    readingTime: "6 min",
    isFeatured: true,
    isDeleted: false,
    keywords: ["Next.js", "Routing", "React"],
    createdAt: new Date("2025-08-01T10:00:00"),
    updatedAt: new Date("2025-08-05T12:30:00"),
  },
  {
    _id: "2",
    title: "Top 10 JavaScript ES6 Features You Must Know",
    slug: "javascript-es6-features",
    description: "Explore the most important ES6 features like let/const, arrow functions, promises, template literals, and more.",
    author: "Sarah Ahmed",
    categories: ["JavaScript", "Programming"],
    featuredImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    status: "published",
    views: 550,
    likes: 47,
    commentsCount: 10,
    readingTime: "8 min",
    isFeatured: false,
    isDeleted: false,
    keywords: ["JavaScript", "ES6", "Programming"],
    createdAt: new Date("2025-07-20T09:15:00"),
    updatedAt: new Date("2025-07-25T18:45:00"),
  },
  {
    _id: "3",
    title: "UI/UX Best Practices for Modern Web Apps",
    slug: "ui-ux-best-practices",
    description: "Learn essential UI/UX principles that improve usability, accessibility, and overall user satisfaction.",
    author: "Michael Khan",
    categories: ["UI/UX", "Design", "Web Development"],
    featuredImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    status: "published",
    views: 780,
    likes: 62,
    commentsCount: 14,
    readingTime: "7 min",
    isFeatured: true,
    isDeleted: false,
    keywords: ["UI/UX", "Design", "Web App"],
    createdAt: new Date("2025-08-10T14:00:00"),
    updatedAt: new Date("2025-08-12T11:30:00"),
  },
  {
    _id: "4",
    title: "Mastering Git and GitHub: A Complete Guide",
    slug: "git-github-complete-guide",
    description: "Everything you need to know about Git and GitHub, including branching, pull requests, and collaboration best practices.",
    author: "Amir Hamza Ismail",
    categories: ["Version Control", "GitHub"],
    featuredImage: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4",
    status: "published",
    views: 1120,
    likes: 98,
    commentsCount: 23,
    readingTime: "10 min",
    isFeatured: true,
    isDeleted: false,
    keywords: ["Git", "GitHub", "Version Control"],
    createdAt: new Date("2025-06-15T08:00:00"),
    updatedAt: new Date("2025-06-20T19:30:00"),
  },
  {
    _id: "5",
    title: "Deploying MERN Stack Apps with Docker",
    slug: "mern-docker-deployment",
    description: "Step-by-step tutorial on containerizing and deploying your MERN stack applications using Docker and Docker Compose.",
    author: "Sophia Rahman",
    categories: ["MERN Stack", "DevOps", "Docker"],
    featuredImage: "https://images.unsplash.com/photo-1585079542156-2755d9c8a094",
    status: "pending",
    views: 210,
    likes: 19,
    commentsCount: 2,
    readingTime: "9 min",
    isFeatured: false,
    isDeleted: false,
    keywords: ["MERN", "Docker", "Deployment"],
    createdAt: new Date("2025-08-20T16:00:00"),
    updatedAt: new Date("2025-08-22T10:45:00"),
  }
];
